# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/York/Digital_Design/VivadoProjects/datapath_standalone/datapath_standalone.cache/wt [current_project]
set_property parent.project_path E:/York/Digital_Design/VivadoProjects/datapath_standalone/datapath_standalone.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo e:/York/Digital_Design/VivadoProjects/datapath_standalone/datapath_standalone.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  E:/York/Digital_Design/VivadoProjects/datapath_standalone/datapath_standalone.srcs/sources_1/imports/new/DigEng.vhd
  E:/York/Digital_Design/VivadoProjects/datapath_standalone/datapath_standalone.srcs/sources_1/imports/VivadoProjects/ALU_standalone/ALU_standalone.srcs/sources_1/imports/ALU.srcs/sources_1/new/ALU.vhd
  E:/York/Digital_Design/VivadoProjects/datapath_standalone/datapath_standalone.srcs/sources_1/imports/VivadoProjects/register_bank_standalone/register_bank_standalone.srcs/sources_1/imports/new/REG_NBIT.vhd
  E:/York/Digital_Design/VivadoProjects/datapath_standalone/datapath_standalone.srcs/sources_1/new/control_logic.vhd
  E:/York/Digital_Design/VivadoProjects/datapath_standalone/datapath_standalone.srcs/sources_1/imports/VivadoProjects/register_bank_standalone/register_bank_standalone.srcs/sources_1/imports/new/reg_bank.vhd
  E:/York/Digital_Design/VivadoProjects/datapath_standalone/datapath_standalone.srcs/sources_1/imports/new/data_path.vhd
  E:/York/Digital_Design/VivadoProjects/datapath_standalone/datapath_standalone.srcs/sources_1/new/Control_datapath.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Control_datapath -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Control_datapath.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Control_datapath_utilization_synth.rpt -pb Control_datapath_utilization_synth.pb"
